### ISSUE TITLE
the css content in html has been wrongly translated 

### ISSUE THREAD

**Issue by lim1208** [googleapis/java-translate#1070]
the translate api: POST https://translation.googleapis.com/v3/projects/PROJECT_NUMBER_OR_ID:translateText, 
this api doc is: https://cloud.google.com/translate/docs/advanced/translating-text-v3#translate_v3_translate_text-drest。

originText:  "<html><style>.md-content.richtext .help-container {background: #f1f1f1}\n</style><body><div class=\"help-container\">test</div></body></html>"

I will translate this originText, the sourceLanguage is "english", the targetLanguage is "ja"。

translatedText: "<html><スタイル>.md-content.richtext .help-container {背景: #f1f1f1}\n</style><body><div class=\"help-container\">テスト</div></body></html>"

you can see <style> mark, it is been translate. I think that css content in html has not need been translated. It should be a bug.

**Comment by mattcarrolldev** [comment]
@lim1208 this repo's issues are for reporting issues with the Java translate library. If you have an issues with the library, please open a new bug and include:

1. A description of the issues with the library
2. the exact steps the lead to the issuing being reproducible
3. what you expected to happen
4. what actually happened

Please also include any information that could help debug like information on your environment, screenshots, etc.
