### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;

### ISSUE THREAD

**Issue by zari786** [googleapis/java-translate#1129]
The translate api is working fine in different OS version but in Samsung android 7 this issue occur

java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;

![Exception](https://user-images.githubusercontent.com/34839678/207047630-d4b83ced-60fa-4e00-b27e-3f85b0fec0ac.PNG)

**Comment by suztomo** [comment]
I'm afraid we are not suitable to support Samsung Android runtime missing `java.time.Duration` class.
