### ISSUE TITLE
Hide Warning

### ISSUE THREAD

**Issue by sova** [googleapis/java-translate#401]
Is there any way to hide or disable the warning that reads
`Jan 25, 2021 8:56:09 PM com.google.cloud.translate.TranslateOptions <init>
WARNING: Ignoring Application Default Credentials GOOGLE_APPLICATION_CREDENTIALS: using explicit setting for API key instead.`

**Comment by telpirion** [comment]
I don't believe so. Using Application Default Credentials is considered a Google Cloud best practice.

See the following:
https://cloud.google.com/docs/authentication
https://cloud.google.com/docs/authentication/production

**Comment by telpirion** [comment]
Additional thought: With Translation Advanced (v3), you can only use service accounts:
https://cloud.google.com/translate/docs/migrate-to-v3#service_accounts
