### ISSUE TITLE
BatchTranslateDocumentRequest.Builder.setParent() should accept LocationName

### ISSUE THREAD

**Issue by telpirion** [googleapis/java-translate#774]
Looking at the generated files, it looks like the BatchTranslateDocumentRequest object still only accepts strings:
https://github.com/googleapis/java-translate/blob/master/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/BatchTranslateDocumentRequest.java#L1607

However, the public source protos have been updated:
https://github.com/googleapis/googleapis/blob/master/google/cloud/translate/v3beta1/translation_service.proto#L1195

**Comment by aribray** [comment]
Hi @Neenu1995, has there been any movement on this? Thanks!

**Comment by Neenu1995** [comment]
Tried regenerating it manually. Same results. Could be an issue with the java microgenerator .
@vam-google Can you take a look please?

**Comment by Neenu1995** [comment]
https://github.com/googleapis/java-translate/blob/master/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/GetSupportedLanguagesRequest.java#L757

https://github.com/googleapis/googleapis/blob/master/google/cloud/translate/v3beta1/translation_service.proto#L394

Same thing is happening here. The generator may not be recognizing Location.

**Comment by Neenu1995** [comment]
https://github.com/googleapis/java-translate/tree/master/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud
Location is being generated in a separate package.

**Comment by Neenu1995** [comment]
Once the translate team make the necessary proto changes and the cl is submitted to the third_party folder, the code will be automatically updated with the required changes in a few hours. 

It might be best to keep the issue until the cl has been submitted.
